### ISSUE TITLE
Discussion on possible feature

### ISSUE THREAD

**Issue by jwoertink** [luislavena/radix#11]
I was thinking of a way to solve an issue I have with Kemal, and it led me to sort of creating a new feature for Radix. I wanted to get your thoughts on it before I spend time putting it in to a PR. This would also need some input from @sdogruyol since it will require a PR on Kemal too.

### The problem
The issue is getting multiple routes defined for the purposes of an API. With the current implementation of Radix, you can't define 2 routes the same (which I actually like). Take this example:

```crystal
# kemal example
api("v1") do
  get "/users" do |env|
    "this is a v1 route"
  end
end

api("v2") do
  get "/users" do |env|
    "this is a v2 route"
  end
end
```

These two routes routes can't go in to the same tree since they are the same. 

### The solution
Imagine a class like

```crystal
module Radix
  class Cluster
  end
end
```

This `Radix::Cluster` class would store a collection of trees. We would add the ability to name a tree, and then the cluster would know how to find a tree by name as well as show you all the trees that contain a specific path. 

How Kemal would need to be updated would be since it only uses a single tree now, it would name that one tree to something like "root". Then the path lookup would do something like

```crystal
# from this
def lookup_route(verb, path)
      @tree.find radix_path(verb, path)
end

# to something like...
def lookup_route(tree_name = "root", verb, path)
    @cluster.find(tree_name, radix_path(verb, path))
end
```

Then in the case of an API, I would just need to create a new tree like `v2_tree = Radix::Tree(Route).new("v2")`. I would add that tree to the cluster, and then tell my routes which tree they go in. Then in some handler I could just say which tree I want to search.

Let me know your thoughts on if this is something you would be cool with, or if it's a horrible idea :p lol

**Comment by sdogruyol** [comment]
I like this 👍

**Comment by luislavena** [comment]
Hello @jwoertink, bear with me as I've some questions before I can fully understand the idea:

What is `api("v1")`? will be `v1` a condition of the URL, or is something provided by the _context_ of the request?

Example: is the final URL `/v1/users` or is always `/users` but should differ routing based on a header or something of the request?

Thank you.

**Comment by jwoertink** [comment]
So in this example, it's actually working code from my new shard [kave](https://github.com/jwoertink/kave). How it works currently is by prepending the version to the path like /v1/users. 

However, in my use case, I don't want to change the path. It needs to stay as /users. The routing would be based on HTTP headers passed in. So a curl example would be

```
curl -H "Accept: application/vnd.api.v2+json" http://localhost:3000/users
```

this call would route to the version 2 of /users.

api() is just the example from my shard, but the main idea is allowing people to use multiple trees in conjunction with each other. This could possibly have sever nice uses.

**Comment by luislavena** [comment]
Hello @jwoertink, sorry for the delayed response on this. Please bear with me as I go over some rationale of Radix and how we currently use it.

Radix as been the extraction of another project (named [Beryl](https://github.com/luislavena/beryl)), which was an early prototype of our routing library.

I had to take a look on how Kemal uses Radix to notice that the request method is prepend to the path, so it builds a unique tree and does a concatenation of path and request method before doing a lookup.

That approach might be efficient to deal with a single tree in memory, but result in more strings being allocated at runtime.

Instead, our usage of Radix is to build independent trees based on the request method, which allow us to have the same `path` for different type of request:

``` crystal
# routeset is a Hash(String, Radix::Tree)
routeset["GET"].add "/path", payload
```

We solved internally the prepend of routes (ie `/api/v1`) by _mounting_ multiple routers on top of another:

``` crystal
class MyApp < Beryl::Router
  routing do
    mount "/api/v1", API::V1::Router
    # ...
  end
end
```

All routes that `API::V1::Router` defines are injected and prepend into `MyApp` routes, so the paths defined by that router will contain `/api/v1`. This is the only time strings are allocated.

This approach to composition allow us have the same router be mounted at different points. Since a router instance is built a that point, we avoid more allocations.

On Radix and other tools, I try to apply the simplicity principle: a tool needs to have a single purpose and be good at it.

Radix applies that: does one thing and tries to be good at it. Using the composition approach in our router, we can solve the first issue you describe without adding special cases to Radix.

That applies to the second scenario. Instead of extending Radix to know about requests, headers and such, we decided to move such responsibility into our router, making it able to apply constraints based on the requests:

``` crystal
class MyApp < Beryl::Router
  routing do
    constraint SubdomainMatcher.new("api"), API::V2::Router
    # ...
  end
end
```

Once constraints are defined, each request is checked against them to determine which router will handle the request.

A matcher can check anything in the `context` (say a request header, path or anything). If the matcher of a constraint is successful, the request (context) is then passed to the instance of that inner router.

Since that inner router was not mounted, it will have it's own Radix::Tree clean and isolated from the parent router (ie `/members` vs `/api/v1/members`)

Of course if `MyApp` was prefixed (mounted as part of another router) that will be taken in consideration.

All router instances are allocated on instantiation of the main router, reducing allocations at runtime.

``` crystal
stack = [
  HTTP::LogHandler.new,
  MyApp.new,
]

server = HTTP::Server.new(9292, stack)
server.listen
```

This approach give us a bit more flexibility as we can combine these rules and the routers independently, use them directly, mount or apply constraints to them.

---

If you reached this point reading, thank you for your patience. Really sorry for this verbose explanation of our usage, but wanted to provide the background on why don't think different dispatching needs to be performed by Radix.

I know this response do not help you solve the particular problem, but I hope might help take a different approach on how it is being solved.

Let me know if you have any question.

Regards and have a nice weekend.

**Comment by jwoertink** [comment]
Awesome! I really appreciate the consideration and response. It actually does make a few things clear for me. I agree that what I was looking for doesn't really need to be in radix. It was more about convienence than anything. Definitely something that can be implemented easily on the side.
